### ISSUE TITLE
AttributeError: type object 'Client' has no attribute '__getattr__'

### ISSUE THREAD

**Issue by ajm188** [ajm188/mqtt-locust#3]
Decided to actually give this a go, looks like the paho mqtt Client does not define `__getattr__`

**Comment by ajm188** [comment]
We may just want to override the publish method, since that's all we really care about for now

**Comment by ajm188** [comment]
It does, however, have a `__getattribute__` ... wtf

**Comment by mtbentley** [comment]
`__getattr__` is called when something doesn't exist.  `__getattribute__` is always called
